---
title: "Assessing the maxrange to SD ratio"
subtitle: "Bainbridge et al.'s data"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```

# Dependencies

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)

```

# Get data

```{r}

dat_bainbridge <- read_csv("../../data/bainbridge et al/processed/data_processed_itemlevel_long.csv") |>
  mutate(min_response = 1,
         max_response = 5)

dat_poopchoc <- read_csv("../../data/not-so-simple-preferences/data_processed_after_exclusions.csv")  |>
  mutate(min_response = 1, 
         max_response = 7) |> # not so simple preferences study (not bainbridge)
  select(id = participant_id,
         min_response,
         max_response,
         poop = classic_poop, 
         chocolate = classic_chocolate,
         pedophile, love, murder, vacation, racist, 
         honest, dishonest, 
         girls_skirts, boys_skirts, cats_legs, fish_legs,
         attention_check1_numeric, 
         attention_check2_numeric) |>
  pivot_longer(cols = c(-id, -min_response, -max_response),
               names_to = "scale",
               values_to = "response") |>
  mutate(subscale = scale)

dat <- bind_rows(dat_bainbridge, 
                 dat_poopchoc)

#dat <- dat_bainbridge

```

# n participants in datasets

```{r}

data_s1 <- read_csv("../../data/bainbridge et al/raw/s1.csv")
data_s2 <- read_csv("../../data/bainbridge et al/raw/s2.csv")
data_s3 <- read_csv("../../data/bainbridge et al/raw/s3.csv")

bind_cols(
  data_s1 |> count(name = "n_study1"),
  data_s2 |> count(name = "n_study2"),
  data_s3 |> count(name = "n_study3")
) |>
  kable() |>
  kable_classic(full_width = FALSE)

```

# n scales

including multi-item self report scales and single item (or small number of items) attitude scales.

```{r}

dat |>
  distinct(scale) |>
  count(name = "n_scales") |>
  kable() |>
  kable_classic(full_width = FALSE)

```

# Range to SD ratio

CIs on M:

$$
m \pm t_{1-\alpha/2, n-1} \left( \frac{s}{\sqrt{n}} \right)
$$

CIs on SD:

$$
\left[ \frac{(n-1)s^2}{\chi^2_{\alpha/2, n-1}}, \frac{(n-1)s^2}{\chi^2_{1-\alpha/2, n-1}} \right]
$$

```{r}

# Function to calculate SD CI bounds
# Returns a tibble to allow for easy unnesting if desired, 
# or can be split into two functions.
calc_sd_ci <- function(x, conf_level = 0.95, side = "lower") {
  n <- sum(!is.na(x))
  df <- n - 1
  sd_val <- sd(x, na.rm = TRUE)
  
  alpha <- 1 - conf_level
  
  if (side == "lower") {
    # Chi-square upper critical value for the lower bound
    chi_val <- qchisq(1 - alpha/2, df)
    return(sqrt((df * sd_val^2) / chi_val))
  } else {
    # Chi-square lower critical value for the upper bound
    chi_val <- qchisq(alpha/2, df)
    return(sqrt((df * sd_val^2) / chi_val))
  }
}

dat_nitems <- dat |>
  count(id, scale, subscale) |>
  group_by(scale, subscale) |>
  summarize(n_items = median(n))

calc_pomp <- function(x, min_possible_response, max_possible_response, n_items) {
  ((x - (min_possible_response*n_items)) / ((max_possible_response*n_items) - (min_possible_response*n_items)))
}

# Smithson-Verkuilen transformation
# to offset values from the [0, 1] limits that Beta regression can't handle 
# often used in Beta regression
calc_sk_transf <- function(y, n){
  (y * (n - 1) + 0.5) / n
}


dat_sumscores <- dat |>
  group_by(id, scale, subscale, min_response, max_response) |>
  summarize(sumscore = sum(response, na.rm = TRUE),
            .groups = "drop") |>
  left_join(dat_nitems, by = c("scale", "subscale")) |>
  mutate(pomp_sumscore = calc_pomp(sumscore, 
                                   min_possible_response = min_response, 
                                   max_possible_response = max_response,
                                   n_items = n_items)) |>
  group_by(scale, subscale) |>
  mutate(n = n()) |>
  ungroup() |>
  mutate(pomp_sumscore_sk_transf = calc_sk_transf(pomp_sumscore, n))

# ggplot(dat_sumscores, aes(pomp_sumscore, pomp_sumscore_sk_transf)) +
#   geom_point()

res <- dat_sumscores |>
  group_by(scale, subscale, n_items, min_response, max_response) |>
  summarize(n = n(),
            m = mean(sumscore),
            sd = sd(sumscore),
            # --- Mean CIs (using t-distribution) ---
            # Standard Error: sd / sqrt(n)
            se = sd / sqrt(n),
            # t-critical value for 95% CI
            t_crit = qt(0.975, df = n - 1),
            m_lower = m - (t_crit * se),
            m_upper = m + (t_crit * se),
            sd_lower = calc_sd_ci(sumscore, side = "lower"),
            sd_upper = calc_sd_ci(sumscore, side = "upper"),
            .groups = "drop") |>
  mutate(min_possible = min_response * n_items, # min possible response for all scales is 1
         max_possible = max_response * n_items, # max possible response for all scales is 1
         max_range = max_possible - min_possible,
         pomp_m = m/max_range,
         romp_m = max_range/m,
         pomp_sd = sd/max_range,
         romp_sd = max_range/sd) |>
  select(-min_possible, -max_possible, -se, -t_crit) |> 
  relocate(sd, .before = sd_lower)

# table
res |>
  mutate_if(is.numeric, roundwork::round_up, digits = 2) |>
  kable() |>
  kable_classic(full_width = FALSE)

temp <- res |>
  mutate_if(is.numeric, roundwork::round_up, digits = 4) |>
  select(scale, subscale, pomp_sd)

```

# POMP distributions

```{r fig.height=12, fig.width=12}

dat_sumscores |>
  group_by(scale) |>
  mutate(mean_pomp_sumscore = mean(pomp_sumscore_sk_transf),
         sd_pomp_sumscore = sd(pomp_sumscore_sk_transf)) |>
  ungroup() |>
  mutate(scale = fct_reorder(scale, mean_pomp_sumscore)) |>
  ggplot(aes(pomp_sumscore_sk_transf)) +
  geom_rect(aes(xmin = mean_pomp_sumscore - sd_pomp_sumscore, 
                xmax = mean_pomp_sumscore + sd_pomp_sumscore, 
                ymin = -Inf, ymax = Inf), 
            fill = "grey90", alpha = 0.5) +
  geom_vline(aes(xintercept = mean_pomp_sumscore), linetype = 'dashed') +
  geom_density(adjust = 2.5) +
  coord_cartesian(xlim = c(0, 1)) +
  theme_linedraw() +
  facet_wrap(~ scale, scales = "free_y") 

```



```{r fig.height=12, fig.width=12}

library(tidyverse)

# 1. Helper function for Beta parameters (Method of Moments)
# We add a tiny offset to avoid exactly 0 or 1, which are undefined in Beta
get_beta_params <- function(x) {
  x <- x * 0.998 + 0.001 
  mu <- mean(x, na.rm = TRUE)
  var <- var(x, na.rm = TRUE)
  
  alpha <- mu * ((mu * (1 - mu) / var) - 1)
  beta <- (1 - mu) * ((mu * (1 - mu) / var) - 1)
  
  return(list(shape1 = alpha, shape2 = beta))
}

# 2. Calculate parameters per scale (facet)
beta_params <- dat_sumscores |>
  group_by(scale) |>
  summarise(params = list(get_beta_params(pomp_sumscore_sk_transf))) |>
  unnest_wider(params)

# 3. Create a high-res grid for the regression lines
grid <- expand_grid(
  scale = unique(dat_sumscores$scale),
  x_val = seq(0.001, 0.999, length.out = 200)
) |>
  left_join(beta_params, by = "scale") |>
  mutate(y_val = dbeta(x_val, shape1, shape2))

# 4. Plot
dat_sumscores |>
  group_by(scale) |>
  mutate(mean_pomp = mean(pomp_sumscore_sk_transf, na.rm = TRUE),
         sd_pomp = sd(pomp_sumscore_sk_transf, na.rm = TRUE)) |>
  ggplot(aes(x = pomp_sumscore_sk_transf)) +
  # Shaded SD region
  geom_rect(aes(xmin = mean_pomp - sd_pomp, xmax = mean_pomp + sd_pomp, 
                ymin = -Inf, ymax = Inf), fill = "grey95") +
  # Dashed density for comparison
  geom_density(aes(y = after_stat(density)), adjust = 1, color = "grey60", linetype = "dashed") +
  # The Beta Regression Line
  geom_line(data = grid, aes(x = x_val, y = y_val), color = "blue", size = 1) +
  geom_vline(aes(xintercept = mean_pomp), linetype = "dashed") +
  theme_linedraw() +
  coord_cartesian(xlim = c(0, 1)) +
  facet_wrap(~ scale, scales = "free_y") +
  labs(x = "POMP sum score", y = "Density")

```


```{r}

dat_sumscores |>
  group_by(scale) |>
  mutate(mean_pomp = mean(pomp_sumscore_sk_transf, na.rm = TRUE),
         sd_pomp = sd(pomp_sumscore_sk_transf, na.rm = TRUE)) |>
  ggplot(aes(x = pomp_sumscore_sk_transf, color = scale, group = scale)) +
  # The Beta Regression Line
  geom_line(data = grid, aes(x = x_val, y = y_val), color = "blue", alpha = 0.3, size = 1) +
  theme_linedraw() +
  labs(x = "POMP sum score", y = "Density") 

```

# POMP SD & ROMP SD

```{r}

# plot
ggplot(res, aes(pomp_sd)) +
  geom_histogram(boundary = 0, binwidth = .025) +
  scale_x_continuous(name = "POMP SD", limits = c(-.05, 1.05), breaks = seq(0, 1, by = .1)) +
  scale_y_continuous(name = "Frequency", breaks = seq(0, 100, by = 5)) +
  theme_linedraw()

# # different implementation of ROMP but same resulting value
# ggplot(res, aes(1/(sd / max_range))) + 
#   geom_histogram(boundary = 0.5, binwidth = 1) +
#   scale_x_continuous(name = "ROMP SD", breaks = 0:10) +
#   scale_y_continuous(name = "Frequency", breaks = seq(0, 100, by = 5)) +
#   theme_linedraw()

# plot
ggplot(res, aes(romp_sd)) +
  geom_histogram(boundary = 0.5, binwidth = 1) +
  scale_x_continuous(name = "Ratio of Maximum Possible SD (ROMP SD)\n(Max range:SD - 'How many SDs wide is the scale range?')", breaks = 0:25) +
  scale_y_continuous(name = "Frequency", breaks = seq(0, 100, by = 5)) +
  theme_linedraw()

ggplot(res, aes(romp_sd/2)) +
  geom_histogram(boundary = 0.5, binwidth = .25) +
  scale_x_continuous(name = "Half-ROMP SD\nrule of thumb for max Cohen's d\n(Max change up or down assuming mean is roughly in the middle))", breaks = seq(0, 20, by = 1)) +
  scale_y_continuous(name = "Frequency", breaks = seq(0, 100, by = 5)) +
  theme_linedraw()

```

# POMP M

```{r}

ggplot(res, aes(pomp_m)) +
  geom_histogram(boundary = 0, binwidth = .025) +
  scale_x_continuous(name = "POMP M", limits = c(-.05, 1.05), breaks = seq(0, 1, by = .1)) +
  scale_y_continuous(name = "Frequency", breaks = seq(0, 100, by = 1)) +
  theme_linedraw()

```

# 95% CIs on M and SD



```{r}



res <- dat_sumscores |>
  group_by(scale, subscale, n_items) |>
  summarize(n = n(),
            m = mean(sumscore),
            sd = sd(sumscore),
            
            .groups = "drop") |>
  mutate(min_possible = 1 * n_items,
         max_possible = 5 * n_items,
         max_range = max_possible - min_possible,
         pomp_m = m/max_range,
         romp_m = max_range/m,
         pomp_sd = sd/max_range,
         romp_sd = max_range/sd) |>
  select(-min_possible, -max_possible) |>
  relocate(max_range, .before = sd)

```